toggle-trample:
    enabled: true

crafting-tweaks:
    enabled: true
    better-chest: true
    name-tag: true
    wool-to-string: true
    saddle: true
    packed-ice: true
    ice: true
    dragons-breath: true
    sponge: true
    dispenser: true
    shulker-shell: true

seed-drop-planting:
    enabled: true

armor-stand-swapping:
    enabled: true

nether-sponge-drying:
    enabled: true

hoe-harvesting:
    enabled: true
    ranges:
        wood: 1
        stone: 1
        iron: 1
        gold: 1
        diamond: 2

lilypad-growing:
    enabled: true